// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package service

import (
	"bytes"
	"fmt"

	"github.com/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type LiveApiService interface {
	// Parameters:
	//  - Pid
	//  - RefId
	//  - RefType
	SetRefId(pid int64, refId string, refType string) (r *ActionResult_, err error)
}

type LiveApiServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewLiveApiServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *LiveApiServiceClient {
	return &LiveApiServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewLiveApiServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *LiveApiServiceClient {
	return &LiveApiServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Pid
//  - RefId
//  - RefType
func (p *LiveApiServiceClient) SetRefId(pid int64, refId string, refType string) (r *ActionResult_, err error) {
	if err = p.sendSetRefId(pid, refId, refType); err != nil {
		return
	}
	return p.recvSetRefId()
}

func (p *LiveApiServiceClient) sendSetRefId(pid int64, refId string, refType string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("SetRefId", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := SetRefIdArgs{
		Pid:     pid,
		RefId:   refId,
		RefType: refType,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *LiveApiServiceClient) recvSetRefId() (value *ActionResult_, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "SetRefId failed: out of sequence response")
		return
	}
	result := SetRefIdResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type LiveApiServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      LiveApiService
}

func (p *LiveApiServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *LiveApiServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *LiveApiServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewLiveApiServiceProcessor(handler LiveApiService) *LiveApiServiceProcessor {

	self2 := &LiveApiServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["SetRefId"] = &liveApiServiceProcessorSetRefId{handler: handler}
	return self2
}

func (p *LiveApiServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type liveApiServiceProcessorSetRefId struct {
	handler LiveApiService
}

func (p *liveApiServiceProcessorSetRefId) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SetRefIdArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("SetRefId", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := SetRefIdResult{}
	var retval *ActionResult_
	var err2 error
	if retval, err2 = p.handler.SetRefId(args.Pid, args.RefId, args.RefType); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing SetRefId: "+err2.Error())
		oprot.WriteMessageBegin("SetRefId", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("SetRefId", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type SetRefIdArgs struct {
	Pid     int64  `thrift:"pid,1,required" json:"pid"`
	RefId   string `thrift:"refId,2,required" json:"refId"`
	RefType string `thrift:"refType,3,required" json:"refType"`
}

func NewSetRefIdArgs() *SetRefIdArgs {
	return &SetRefIdArgs{}
}

func (p *SetRefIdArgs) GetPid() int64 {
	return p.Pid
}

func (p *SetRefIdArgs) GetRefId() string {
	return p.RefId
}

func (p *SetRefIdArgs) GetRefType() string {
	return p.RefType
}
func (p *SetRefIdArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *SetRefIdArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Pid = v
	}
	return nil
}

func (p *SetRefIdArgs) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.RefId = v
	}
	return nil
}

func (p *SetRefIdArgs) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.RefType = v
	}
	return nil
}

func (p *SetRefIdArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SetRefId_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *SetRefIdArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("pid", thrift.I64, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:pid: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.Pid)); err != nil {
		return fmt.Errorf("%T.pid (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:pid: %s", p, err)
	}
	return err
}

func (p *SetRefIdArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("refId", thrift.STRING, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:refId: %s", p, err)
	}
	if err := oprot.WriteString(string(p.RefId)); err != nil {
		return fmt.Errorf("%T.refId (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:refId: %s", p, err)
	}
	return err
}

func (p *SetRefIdArgs) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("refType", thrift.STRING, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:refType: %s", p, err)
	}
	if err := oprot.WriteString(string(p.RefType)); err != nil {
		return fmt.Errorf("%T.refType (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:refType: %s", p, err)
	}
	return err
}

func (p *SetRefIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetRefIdArgs(%+v)", *p)
}

type SetRefIdResult struct {
	Success *ActionResult_ `thrift:"success,0" json:"success"`
}

func NewSetRefIdResult() *SetRefIdResult {
	return &SetRefIdResult{}
}

var SetRefIdResult_Success_DEFAULT *ActionResult_

func (p *SetRefIdResult) GetSuccess() *ActionResult_ {
	if !p.IsSetSuccess() {
		return SetRefIdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SetRefIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetRefIdResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *SetRefIdResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &ActionResult_{}
	if err := p.Success.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Success, err)
	}
	return nil
}

func (p *SetRefIdResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SetRefId_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *SetRefIdResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Success, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *SetRefIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetRefIdResult(%+v)", *p)
}
